include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Keep CI green while we iterate; treat infos as non-blocking.
    info: ignore
    todo: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
